#define yy_create_buffer rig_yy_create_buffer
#define yy_delete_buffer rig_yy_delete_buffer
#define yy_scan_buffer rig_yy_scan_buffer
#define yy_scan_string rig_yy_scan_string
#define yy_scan_bytes rig_yy_scan_bytes
#define yy_flex_debug rig_yy_flex_debug
#define yy_init_buffer rig_yy_init_buffer
#define yy_flush_buffer rig_yy_flush_buffer
#define yy_load_buffer_state rig_yy_load_buffer_state
#define yy_switch_to_buffer rig_yy_switch_to_buffer
#define yyin rig_yyin
#define yyleng rig_yyleng
#define yylex rig_yylex
#define yyout rig_yyout
#define yyrestart rig_yyrestart
#define yytext rig_yytext
#define yylineno rig_yylineno

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/fillods/RA/rigctrl/hamlib_cvsroot/hamlib/tests/lex.rig_yy.c,v 1.1.2.1 2003-02-25 15:59:55 dedmons Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 152
#define YY_END_OF_BUFFER 153
static yyconst short int yy_acclist[385] =
    {   0,
      153,  151,  152,    1,  151,  152,  152,  151,  152,  151,
      152,  151,  152,  151,  152,  151,  152,  148,  151,  152,
      149,  151,  152,  149,  151,  152,  149,  151,  152,  149,
      151,  152,  149,  151,  152,  149,  151,  152,  149,  151,
      152,  149,  151,  152,  149,  151,  152,  149,  151,  152,
      149,  151,  152,  149,  151,  152,  149,  151,  152,  149,
      151,  152,  149,  151,  152,  149,  151,  152,  149,  151,
      152,  149,  151,  152,  149,  151,  152,  149,  151,  152,
      149,  151,  152,  149,  151,  152,  149,  151,  152,  149,
      151,  152,  149,  151,  152,  149,  151,  152,  149,  151,

      152,  149,  151,  152,    1,  144,  131,  134,  132,  133,
      145,  146,  148,  149,  149,    3,  149,    8,  149,   11,
      149,  149,  149,  138,  149,  149,  149,  149,  149,    2,
      149,  149,  149,  149,    7,  149,  149,  149,   10,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
       25,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  145,  150,  145,  146,  147,  109,  113,  121,
       51,   69,   63,   93,   52,   70,   64,   38,   44,   74,
      110,  117,  125,   39,   99,   40,  100,   50,   68,   56,
       80,  114,  118,  129,   45,   57,  105,   46,   58,  106,

       86,   13,  149,  135,  149,   18,  149,  122,  126,  130,
       75,   81,   87,   76,   94,   82,   88,   98,  104,  136,
      149,  149,   33,  149,  107,  111,  119,   48,   66,   60,
       90,   49,   67,   61,   35,   41,   71,  108,  115,  123,
       36,   96,   37,   79,   97,   47,   65,   53,   77,  112,
      116,  127,   42,   54,  102,   43,   55,  103,   62,   59,
       83,  149,  149,  149,  149,  149,   12,  149,  149,  149,
      137,  149,   17,  149,  120,  124,  128,   72,   78,   84,
       73,   91,   85,   92,   89,   95,  101,  149,   20,  149,
      149,  149,  149,  149,  149,  149,  149,   27,  149,  149,

      149,  149,   30,  149,  149,  149,   32,  149,  145,  145,
      146,  146,   14,  149,    4,  149,  149,    6,  149,  149,
        9,  149,   15,  149,   16,  149,   19,  149,   21,  149,
      149,  149,  149,  149,   24,  149,  149,  149,  149,  149,
      149,   31,  149,  140,  149,  145,  146,    5,  149,  139,
      149,  149,   22,  149,  149,  149,   26,  149,  149,  149,
       28,  149,   29,  149,  149,  149,   23,  149,  149,  141,
      149,  142,  149,  149,  149,  149,  149,  149,  149,  143,
      149,  149,   34,  149
    } ;

static yyconst short int yy_accept[310] =
    {   0,
        1,    1,    1,    2,    4,    7,    8,   10,   12,   14,
       16,   18,   21,   24,   27,   30,   33,   36,   39,   42,
       45,   48,   51,   54,   57,   60,   63,   66,   69,   72,
       75,   78,   81,   84,   87,   90,   93,   96,   99,  102,
      105,  106,  106,  107,  108,  108,  108,  109,  110,  111,
      112,  112,  113,  114,  114,  114,  115,  115,  115,  115,
      116,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      120,  122,  123,  124,  126,  127,  127,  127,  127,  127,
      128,  129,  130,  130,  130,  130,  130,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  133,  134,  135,  137,

      138,  139,  141,  142,  143,  144,  145,  146,  146,  146,
      146,  146,  147,  148,  149,  150,  151,  153,  154,  155,
      156,  157,  158,  159,  160,  161,  162,  163,  164,  164,
      164,  165,  167,  167,  168,  169,  170,  171,  173,  174,
      175,  177,  178,  179,  180,  181,  182,  183,  184,  185,
      186,  187,  188,  190,  191,  192,  193,  194,  195,  196,
      197,  198,  199,  200,  201,  202,  204,  206,  208,  209,
      210,  211,  212,  213,  214,  216,  217,  218,  219,  220,
      222,  223,  225,  226,  227,  228,  230,  231,  232,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,

      246,  248,  249,  250,  251,  252,  253,  254,  255,  256,
      257,  258,  259,  260,  261,  262,  263,  264,  265,  266,
      267,  269,  270,  271,  273,  275,  276,  277,  278,  279,
      280,  281,  283,  284,  285,  286,  287,  288,  289,  291,
      292,  293,  294,  295,  296,  297,  298,  300,  301,  302,
      303,  305,  306,  307,  309,  310,  312,  312,  313,  315,
      317,  318,  320,  321,  323,  325,  327,  329,  331,  332,
      333,  334,  335,  337,  338,  339,  340,  341,  342,  344,
      346,  348,  350,  352,  353,  355,  356,  357,  359,  360,
      361,  363,  365,  366,  367,  369,  370,  372,  374,  375,

      376,  377,  378,  379,  380,  382,  383,  385,  385
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    6,    7,    8,    9,    9,   10,
        9,    9,    9,    9,    9,    9,    9,    1,    1,   11,
       12,   13,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   17,   17,   22,   23,   24,   17,   17,   17,
       17,   25,   26,   27,   28,   17,   29,   17,   30,   17,
        1,    1,    1,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   17,   41,   42,   43,   44,
       45,   46,   17,   47,   48,   49,   50,   17,   51,   52,
       53,   54,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        2,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst short int yy_base[313] =
    {   0,
        0,    0,  252,  891,  230,  891,   52,   52,   59,   63,
      222,   67,   70,   78,   87,   96,  102,  109,  123,  129,
      135,  141,  149,  161,  170,  197,  176,  182,  188,  203,
      209,  246,  232,  273,  252,  311,  226,  251,  180,  190,
      222,   89,  891,  891,   92,  290,  891,  891,  891,  293,
       81,  297,  321,  114,  319,    0,  321,  148,  325,   82,
      231,  328,   46,  152,  337,  345,  348,  350,   51,  232,
      248,  303,  323,  267,  340,  235,  364,  374,  187,  328,
      349,  352,  367,  369,  371,  373,  366,  383,  295,  376,
      386,  389,  391,  395,  411,  388,  402,  394,  397,  403,

      412,  413,  420,  426,  432,  431,  437,  454,  457,  133,
      467,  462,  449,  461,  468,  473,  419,  474,  482,  485,
      490,  491,  499,  498,  504,  516,  517,  547,  543,   64,
      891,  557,  545,  559,  891,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  527,  533,  534,  891,  891,
      891,  891,  891,  891,  891,  891,  891,  891,  891,  539,
      555,  544,  891,  891,  891,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  891,  891,  891,  891,  891,

      891,  891,  891,  891,  891,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  552,  558,  545,  564,  565,
      570,  573,  578,  579,  585,  891,  891,  891,  891,  891,
      891,  891,  891,  891,  891,  891,  891,  590,  593,  596,
      602,  612,  607,  613,  619,  626,  632,  629,  635,  644,
      641,  647,   22,  650,  689,  691,  693,  695,  663,  668,
      669,  675,  676,  681,  687,  688,  693,  694,  699,  707,
      700,  715,  710,  716,  721,  727,  730,  735,  736,    0,
      776,  744,  745,  757,  751,  763,  758,  766,  776,  777,
      771,  782,  783,  789,  790,  801,  796,  802,  807,  808,

      821,  815,  816,  827,  828,  833,  834,  891,  882,  884,
      887,   55
    } ;

static yyconst short int yy_def[313] =
    {   0,
      308,    1,  308,  308,  308,  308,  309,  308,  308,  308,
      308,  308,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,   36,   36,   36,   36,
      308,  309,  308,  308,  308,  308,  308,  308,  308,  308,
      311,  308,  308,  308,  308,  312,  308,  308,  308,   36,
       36,  308,  308,  308,  308,  308,  308,  308,  308,   36,
       36,   36,   36,   36,   36,  308,  308,  308,  308,   36,
       36,   36,  308,  308,  308,  308,   36,  308,  308,  308,
      308,  308,  308,  308,  308,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,  308,  308,  308,
      308,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,  308,  308,  311,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,   36,   36,   36,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,   36,
       36,   36,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,  312,   36,  308,  308,  308,  308,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,  312,
      308,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,    0,  308,  308,
      308,  308
    } ;

static yyconst short int yy_nxt[946] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   12,
        4,    4,    4,   13,   14,   15,   16,   16,   17,   18,
       19,   16,   20,   21,   22,   16,   16,   23,   16,   16,
       16,   24,   25,   26,   27,   28,   29,   16,   30,   31,
       32,   33,   34,   16,   35,   36,   37,   38,   39,   40,
       16,   16,   16,   16,   43,   43,   44,   56,   45,  149,
       46,   46,  280,   47,   48,   45,  131,   46,   46,  150,
       49,   50,   50,   52,  165,   53,   53,   55,   56,   56,
       57,   58,   59,  131,   54,   62,   56,   56,   63,   64,
       65,   43,   43,   61,   66,   56,   56,   67,   68,   69,

       50,   50,   54,  308,   56,   56,  308,  308,  308,  308,
       56,   56,  308,  308,  308,   70,  308,   56,   56,  308,
      308,  308,  134,  134,   60,   71,   60,   72,   60,   73,
      308,   56,   56,  308,  308,  308,  308,   56,   56,  308,
      308,  308,   76,   56,   56,   77,   78,   79,  308,   56,
       56,  308,  308,  308,   75,   80,  308,   56,   56,  308,
      308,  308,  141,  142,  232,  151,  233,   81,   83,   56,
       56,   84,   85,   86,   82,  152,   74,   88,   56,   56,
       89,   90,   91,  308,   56,   56,  308,  308,  308,  308,
       56,   56,  308,  308,  308,  308,   56,   56,  308,  308,

      308,  178,  179,   87,   92,   56,   56,   93,   94,   95,
      308,   56,   56,  308,  308,  308,  308,   56,   56,  308,
      308,  308,   60,   41,  125,  100,   60,  126,   96,   51,
      102,   41,   60,  101,   60,  103,   60,  127,  104,  308,
       56,   56,  308,  308,  308,   97,   98,   99,  169,  170,
      171,  308,  105,  308,   56,   56,  308,  308,  308,  308,
       56,   56,  308,  308,  308,  120,  106,  308,   60,  308,
       60,  121,   60,   60,   60,   60,   60,   60,   60,  107,
      108,   56,   56,  109,  110,  111,  122,  308,  116,  123,
       60,  308,   60,   60,   60,   60,   52,   60,   46,   46,

      124,  128,  128,  308,  112,  132,  132,   54,  113,   60,
      129,   60,  308,   60,  133,  114,  308,  115,  308,   56,
       56,  308,  308,  308,  166,   54,  197,   52,  129,   53,
       53,  308,  133,  135,  136,  138,  139,  198,   54,  143,
      144,  146,  137,  147,  140,   60,  308,   60,  145,   60,
      153,  148,  154,  117,  168,  118,   54,  119,  156,  157,
      155,  159,  160,  162,  163,   60,  182,   60,  158,   60,
       60,  161,   60,  164,   60,  181,  167,  172,  173,  174,
      308,  180,   60,  308,   60,  308,   60,  175,  176,  177,
      308,   60,  308,   60,   60,   60,   60,  308,   60,  183,

      184,  186,  187,  189,  190,  191,  192,  199,   60,  185,
       60,  188,   60,  308,  194,  193,  195,  201,  200,  202,
      204,  205,  207,  208,  213,  196,  210,  211,  203,  216,
       60,  206,   60,  209,   60,  217,   60,  212,   60,   60,
      218,   60,  214,   60,   60,  219,   60,   60,   60,   60,
      308,  220,  308,  215,   60,   60,   60,   60,   60,   60,
      221,   60,   60,   60,   60,   60,   60,  222,   60,  225,
       60,  223,   60,   60,   60,   60,   60,   60,   60,   60,
      234,   60,  308,   60,  224,  226,  227,  228,  229,  230,
      231,  239,  240,   60,  308,   60,  241,  308,  235,  236,

      237,  238,  242,   60,   60,   60,   60,   60,   60,  244,
       60,  308,  243,  308,   60,   60,   60,   60,   60,   60,
      245,  246,  247,  248,   60,  253,   60,   60,   60,   60,
      251,   60,   60,   60,   60,   60,   60,   60,  250,  249,
       60,   60,   60,   60,   60,   60,   60,  252,   60,  254,
       60,  255,  255,  258,  258,  128,  128,  308,   60,   60,
       60,   60,   60,   60,  129,  256,  256,  134,  134,   60,
      308,   60,  308,   60,  257,   60,   60,   60,   60,   60,
       60,   60,  129,   60,  259,   60,   60,   60,   60,   60,
       60,  262,  257,  260,   60,  308,   60,   60,   60,   60,

       60,   60,   60,  308,   60,  261,  263,   60,   60,   60,
       60,   60,   60,  264,   60,   60,   60,   60,  265,   60,
       60,   60,   60,   60,   60,   60,  266,   60,  308,   60,
      308,   60,   60,  267,   60,   60,   60,   60,   60,   60,
       60,  308,   60,  269,   60,  268,   60,  270,   60,   60,
      271,   60,  308,   60,   60,   60,   60,   60,   60,   60,
      272,   60,  275,   60,  308,   60,  308,  273,   60,  274,
       60,   60,   60,   60,   60,  276,   60,   60,   60,   60,
      278,   60,  279,   60,  277,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,  308,   60,  255,  255,  256,

      256,  281,  281,  258,  258,   60,  308,   60,  257,   60,
       60,   60,   60,   60,   60,   60,  282,   60,   60,   60,
       60,   60,   60,   60,  308,   60,  257,   60,  283,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,  286,   60,   60,   60,   60,  284,  285,   60,
      287,   60,   60,   60,   60,  289,   60,   60,   60,   60,
       60,   60,   60,   60,  288,   60,  290,   60,  308,   60,
      308,   60,   60,   60,   60,  291,   60,   60,   60,   60,
       60,   60,   60,  292,  281,  281,   60,   60,   60,   60,
       60,   60,  293,   60,  308,   60,  308,   60,  294,   60,

       60,   60,   60,   60,   60,   60,  295,   60,   60,   60,
       60,  296,   60,   60,  297,   60,  308,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,  298,
      299,   60,   60,   60,   60,   60,   60,  300,   60,  302,
       60,  308,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,  301,  303,   60,   60,   60,
       60,   60,  305,   60,  304,   60,  308,   60,  306,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,  307,   42,   42,   42,   60,   60,  130,  130,  130,
        3,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308
    } ;

static yyconst short int yy_chk[946] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    8,  312,    8,   63,
        8,    8,  253,    8,    9,    9,  130,    9,    9,   63,
        9,   10,   10,   12,   69,   12,   12,   13,   13,   13,
       13,   13,   13,   51,   12,   14,   14,   14,   14,   14,
       14,   42,   42,   13,   15,   15,   15,   15,   15,   15,

       45,   45,   12,   16,   16,   16,   16,   16,   16,   17,
       17,   17,   17,   17,   17,   15,   18,   18,   18,   18,
       18,   18,   54,   54,   60,   17,   60,   17,   60,   18,
       19,   19,   19,   19,   19,   19,   20,   20,   20,   20,
       20,   20,   21,   21,   21,   21,   21,   21,   22,   22,
       22,   22,   22,   22,   20,   21,   23,   23,   23,   23,
       23,   23,   58,   58,  110,   64,  110,   22,   24,   24,
       24,   24,   24,   24,   23,   64,   19,   25,   25,   25,
       25,   25,   25,   27,   27,   27,   27,   27,   27,   28,
       28,   28,   28,   28,   28,   29,   29,   29,   29,   29,

       29,   79,   79,   24,   26,   26,   26,   26,   26,   26,
       30,   30,   30,   30,   30,   30,   31,   31,   31,   31,
       31,   31,   39,   41,   39,   27,   39,   39,   26,   11,
       29,    5,   40,   28,   40,   29,   40,   40,   30,   33,
       33,   33,   33,   33,   33,   26,   26,   26,   76,   76,
       76,    3,   31,   32,   32,   32,   32,   32,   32,   35,
       35,   35,   35,   35,   35,   37,   32,    0,   37,    0,
       37,   37,   37,   61,   70,   61,   70,   61,   70,   33,
       34,   34,   34,   34,   34,   34,   38,    0,   35,   38,
       71,    0,   71,   38,   71,   38,   46,   38,   46,   46,

       38,   50,   50,    0,   34,   52,   52,   46,   34,   74,
       50,   74,    0,   74,   52,   34,    0,   34,   36,   36,
       36,   36,   36,   36,   72,   46,   89,   53,   50,   53,
       53,    0,   52,   55,   55,   57,   57,   89,   53,   59,
       59,   62,   55,   62,   57,   72,    0,   72,   59,   72,
       65,   62,   65,   36,   75,   36,   53,   36,   66,   66,
       65,   67,   67,   68,   68,   73,   82,   73,   66,   73,
       80,   67,   80,   68,   80,   81,   73,   77,   77,   77,
        0,   80,   75,    0,   75,    0,   75,   78,   78,   78,
        0,   81,    0,   81,   82,   81,   82,    0,   82,   83,

       83,   84,   84,   85,   85,   86,   86,   90,   87,   83,
       87,   84,   87,    0,   88,   86,   88,   91,   90,   91,
       92,   92,   93,   93,   95,   88,   94,   94,   91,   96,
       96,   92,   96,   93,   96,   97,   98,   94,   98,   99,
       98,   99,   95,   99,   97,  100,   97,  100,   97,  100,
        0,  101,    0,   95,  101,  102,  101,  102,  101,  102,
      103,  117,  103,  117,  103,  117,  103,  104,  104,  107,
      104,  105,  104,  106,  105,  106,  105,  106,  105,  107,
      111,  107,    0,  107,  106,  108,  108,  108,  109,  109,
      109,  113,  113,  113,    0,  113,  114,    0,  111,  111,

      111,  112,  115,  114,  112,  114,  112,  114,  112,  116,
      115,    0,  115,    0,  115,  116,  118,  116,  118,  116,
      118,  119,  120,  121,  119,  126,  119,  120,  119,  120,
      124,  120,  121,  122,  121,  122,  121,  122,  123,  122,
      124,  123,  124,  123,  124,  123,  125,  125,  125,  127,
      125,  129,  129,  133,  133,  128,  128,    0,  126,  127,
      126,  127,  126,  127,  128,  132,  132,  134,  134,  166,
        0,  166,    0,  166,  132,  167,  168,  167,  168,  167,
      168,  180,  128,  180,  181,  180,  182,  218,  182,  218,
      182,  218,  132,  216,  216,    0,  216,  181,  216,  181,

      217,  181,  217,    0,  217,  217,  219,  220,  219,  220,
      219,  220,  221,  220,  221,  222,  221,  222,  222,  222,
      223,  224,  223,  224,  223,  224,  223,  225,    0,  225,
        0,  225,  238,  238,  238,  239,  238,  239,  240,  239,
      240,    0,  240,  241,  241,  240,  241,  242,  241,  243,
      243,  243,    0,  243,  242,  244,  242,  244,  242,  244,
      244,  245,  247,  245,    0,  245,    0,  245,  246,  246,
      246,  248,  246,  248,  247,  248,  247,  249,  247,  249,
      250,  249,  252,  251,  249,  251,  250,  251,  250,  252,
      250,  252,  254,  252,  254,    0,  254,  255,  255,  256,

      256,  257,  257,  258,  258,  259,    0,  259,  256,  259,
      260,  261,  260,  261,  260,  261,  261,  262,  263,  262,
      263,  262,  263,  264,    0,  264,  256,  264,  263,  265,
      266,  265,  266,  265,  266,  267,  268,  267,  268,  267,
      268,  269,  271,  269,  271,  269,  271,  269,  270,  270,
      272,  270,  273,  270,  273,  275,  273,  272,  274,  272,
      274,  272,  274,  275,  274,  275,  276,  275,    0,  276,
        0,  276,  277,  276,  277,  277,  277,  278,  279,  278,
      279,  278,  279,  278,  281,  281,  282,  283,  282,  283,
      282,  283,  284,  285,    0,  285,    0,  285,  286,  284,

      287,  284,  287,  284,  287,  286,  287,  286,  288,  286,
      288,  289,  288,  291,  290,  291,    0,  291,  289,  290,
      289,  290,  289,  290,  292,  293,  292,  293,  292,  293,
      294,  294,  295,  294,  295,  294,  295,  296,  297,  300,
      297,    0,  297,  296,  298,  296,  298,  296,  298,  299,
      300,  299,  300,  299,  300,  299,  301,  302,  303,  302,
      303,  302,  303,  301,  302,  301,    0,  301,  304,  304,
      305,  304,  305,  304,  305,  306,  307,  306,  307,  306,
      307,  306,  309,  309,  309,  310,  310,  311,  311,  311,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
//#include <hamlib/rig.h>

#include "rigcmd.h"

#define YY_ALWAYS_INTERACTIVE 1
#line 755 "lex.rig_yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 12 "scanner.l"


#line 909 "lex.rig_yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 891 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 14 "scanner.l"
/* empty */;
	YY_BREAK
/* Keywords */
case 2:
#line 17 "scanner.l"
case 3:
YY_RULE_SETUP
#line 17 "scanner.l"
{ return RIG_TOKEN_AM; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "scanner.l"
{ return RIG_TOKEN_CALL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "scanner.l"
{ return RIG_TOKEN_CTCSS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "scanner.l"
{ return RIG_TOKEN_CURR; }
	YY_BREAK
case 7:
#line 22 "scanner.l"
case 8:
YY_RULE_SETUP
#line 22 "scanner.l"
{ return RIG_TOKEN_CW; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "scanner.l"
{ return RIG_TOKEN_EXIT; }
	YY_BREAK
case 10:
#line 25 "scanner.l"
case 11:
YY_RULE_SETUP
#line 25 "scanner.l"
{ return RIG_TOKEN_FM; }
	YY_BREAK
case 12:
#line 27 "scanner.l"
case 13:
#line 28 "scanner.l"
case 14:
YY_RULE_SETUP
#line 28 "scanner.l"
{ return RIG_TOKEN_RTTY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "scanner.l"
{ return RIG_TOKEN_HELP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "scanner.l"
{ return RIG_TOKEN_INIT; }
	YY_BREAK
case 17:
#line 32 "scanner.l"
case 18:
YY_RULE_SETUP
#line 32 "scanner.l"
{ return RIG_TOKEN_LSB; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "scanner.l"
{ return RIG_TOKEN_MAIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "scanner.l"
{ return RIG_TOKEN_MEM; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "scanner.l"
{ return RIG_TOKEN_MENU; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "scanner.l"
{ yylval.val = 0; return RIG_TOKEN_MODEL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "scanner.l"
{ return RIG_TOKEN_OFFSET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "scanner.l"
{ yylval.val = 0; return RIG_TOKEN_PORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "scanner.l"
{ return RIG_TOKEN_PM; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "scanner.l"
{ return RIG_TOKEN_PRINT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "scanner.l"
{ yylval.val = 0; return RIG_TOKEN_RIG; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "scanner.l"
{ return RIG_TOKEN_SETUP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "scanner.l"
{ return RIG_TOKEN_SHIFT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "scanner.l"
{ return RIG_TOKEN_SUB; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "scanner.l"
{ return RIG_TOKEN_TONE; }
	YY_BREAK
case 32:
#line 47 "scanner.l"
case 33:
YY_RULE_SETUP
#line 47 "scanner.l"
{ return RIG_TOKEN_USB; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "scanner.l"
{ return RIG_TOKEN_RIGDEFAULT; }
	YY_BREAK
/* Super functions available only via the parser! */
case 35:
#line 52 "scanner.l"
case 36:
#line 53 "scanner.l"
case 37:
#line 54 "scanner.l"
case 38:
#line 55 "scanner.l"
case 39:
#line 56 "scanner.l"
case 40:
YY_RULE_SETUP
#line 56 "scanner.l"
{ return RIG_TOKEN_BEQA; }	// A copied to B 
	YY_BREAK
case 41:
#line 58 "scanner.l"
case 42:
#line 59 "scanner.l"
case 43:
#line 60 "scanner.l"
case 44:
#line 61 "scanner.l"
case 45:
#line 62 "scanner.l"
case 46:
YY_RULE_SETUP
#line 62 "scanner.l"
{ return RIG_TOKEN_CEQA; }	// A copied to C
	YY_BREAK
case 47:
#line 64 "scanner.l"
case 48:
#line 65 "scanner.l"
case 49:
#line 66 "scanner.l"
case 50:
#line 67 "scanner.l"
case 51:
#line 68 "scanner.l"
case 52:
YY_RULE_SETUP
#line 68 "scanner.l"
{ return RIG_TOKEN_AEQB; }	// B copied to A
	YY_BREAK
case 53:
#line 70 "scanner.l"
case 54:
#line 71 "scanner.l"
case 55:
#line 72 "scanner.l"
case 56:
#line 73 "scanner.l"
case 57:
#line 74 "scanner.l"
case 58:
YY_RULE_SETUP
#line 74 "scanner.l"
{ return RIG_TOKEN_CEQB; }	// B copied to C
	YY_BREAK
case 59:
#line 76 "scanner.l"
case 60:
#line 77 "scanner.l"
case 61:
#line 78 "scanner.l"
case 62:
#line 79 "scanner.l"
case 63:
#line 80 "scanner.l"
case 64:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return RIG_TOKEN_AEQC; }	// C copied to A
	YY_BREAK
case 65:
#line 82 "scanner.l"
case 66:
#line 83 "scanner.l"
case 67:
#line 84 "scanner.l"
case 68:
#line 85 "scanner.l"
case 69:
#line 86 "scanner.l"
case 70:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return RIG_TOKEN_BEQC; }	// C copied to B
	YY_BREAK
case 71:
#line 88 "scanner.l"
case 72:
#line 89 "scanner.l"
case 73:
#line 90 "scanner.l"
case 74:
#line 91 "scanner.l"
case 75:
#line 92 "scanner.l"
case 76:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return RIG_TOKEN_MEQA; }	// A copied to M
	YY_BREAK
case 77:
#line 94 "scanner.l"
case 78:
#line 95 "scanner.l"
case 79:
#line 96 "scanner.l"
case 80:
#line 97 "scanner.l"
case 81:
#line 98 "scanner.l"
case 82:
YY_RULE_SETUP
#line 98 "scanner.l"
{ return RIG_TOKEN_MEQB; }	// B copied to M
	YY_BREAK
case 83:
#line 100 "scanner.l"
case 84:
#line 101 "scanner.l"
case 85:
#line 102 "scanner.l"
case 86:
#line 103 "scanner.l"
case 87:
#line 104 "scanner.l"
case 88:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return RIG_TOKEN_MEQC; }	// C copied to M
	YY_BREAK
case 89:
#line 106 "scanner.l"
case 90:
#line 107 "scanner.l"
case 91:
#line 108 "scanner.l"
case 92:
#line 109 "scanner.l"
case 93:
#line 110 "scanner.l"
case 94:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return RIG_TOKEN_AEQM; }	// M copied to A
	YY_BREAK
case 95:
#line 112 "scanner.l"
case 96:
#line 113 "scanner.l"
case 97:
#line 114 "scanner.l"
case 98:
#line 115 "scanner.l"
case 99:
#line 116 "scanner.l"
case 100:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return RIG_TOKEN_BEQM; }	// M copied to B
	YY_BREAK
case 101:
#line 118 "scanner.l"
case 102:
#line 119 "scanner.l"
case 103:
#line 120 "scanner.l"
case 104:
#line 121 "scanner.l"
case 105:
#line 122 "scanner.l"
case 106:
YY_RULE_SETUP
#line 122 "scanner.l"
{ return RIG_TOKEN_CEQM; }	// M copied to C
	YY_BREAK
case 107:
#line 124 "scanner.l"
case 108:
#line 125 "scanner.l"
case 109:
#line 126 "scanner.l"
case 110:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return RIG_TOKEN_ASWB; }	// A->tmp, B->A, tmp->B
	YY_BREAK
case 111:
#line 128 "scanner.l"
case 112:
#line 129 "scanner.l"
case 113:
#line 130 "scanner.l"
case 114:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return RIG_TOKEN_ASWC; }	// A->tmp, C->A, tmp->C
	YY_BREAK
case 115:
#line 132 "scanner.l"
case 116:
#line 133 "scanner.l"
case 117:
#line 134 "scanner.l"
case 118:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return RIG_TOKEN_BSWC; }	// B->tmp, C->B, tmp->C
	YY_BREAK
case 119:
#line 136 "scanner.l"
case 120:
#line 137 "scanner.l"
case 121:
#line 138 "scanner.l"
case 122:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return RIG_TOKEN_ASWM; }	// A->tmp, M->A, tmp->M
	YY_BREAK
case 123:
#line 140 "scanner.l"
case 124:
#line 141 "scanner.l"
case 125:
#line 142 "scanner.l"
case 126:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return RIG_TOKEN_BSWM; }	// B->tmp, M->B, tmp->M
	YY_BREAK
case 127:
#line 144 "scanner.l"
case 128:
#line 145 "scanner.l"
case 129:
#line 146 "scanner.l"
case 130:
YY_RULE_SETUP
#line 146 "scanner.l"
{ return RIG_TOKEN_CSWM; }	// C->tmp, M->C, tmp->M
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return RIG_TOKEN_PLUSPLUS; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return RIG_TOKEN_MINUSMINUS; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return RIG_TOKEN_MINUSEQ; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return RIG_TOKEN_PLUSEQ; }
	YY_BREAK
/* constants for us lazy people */
case 135:
YY_RULE_SETUP
#line 154 "scanner.l"
{ yylval.fval = 1e9; return RIG_TOKEN_GHZ; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 155 "scanner.l"
{ yylval.fval = 1e6; return RIG_TOKEN_MHZ; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 156 "scanner.l"
{ yylval.fval = 1e3; return RIG_TOKEN_KHZ; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 157 "scanner.l"
{ yylval.fval = 1e0; return RIG_TOKEN_HZ; }
	YY_BREAK
/* models (only a few are lowercase;  the rest are a table */
case 139:
YY_RULE_SETUP
#line 160 "scanner.l"
{ yylval.model = RIG_MODEL_DUMMY; return RIG_LEX_MODEL; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 161 "scanner.l"
{ yylval.model = RIG_MODEL_TS2K; return RIG_LEX_MODEL; }
	YY_BREAK
case 141:
#line 163 "scanner.l"
case 142:
#line 164 "scanner.l"
case 143:
YY_RULE_SETUP
#line 164 "scanner.l"
{ yylval.model = RIG_MODEL_RPC; return RIG_LEX_MODEL; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 167 "scanner.l"
{	/* we have to lop off the " on either side... :( */
		yylval.txt = strdup(&yytext[1]);
		yylval.txt[yyleng-2] = '\0';
		if(yytext[yyleng-2] == '\n');
		return RIG_TOKEN_STRING;
	}
	YY_BREAK
case 145:
#line 175 "scanner.l"
case 146:
#line 176 "scanner.l"
case 147:
YY_RULE_SETUP
#line 176 "scanner.l"
{ yylval.fval = atof(yytext); return RIG_TOKEN_FLOAT; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 178 "scanner.l"
{ yylval.val = atoi(yytext); return RIG_TOKEN_INT; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 180 "scanner.l"
{ return keyword(yytext); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 182 "scanner.l"
;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 185 "scanner.l"
{ return yytext[0]; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 188 "scanner.l"
ECHO;
	YY_BREAK
#line 1502 "lex.rig_yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 308);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 188 "scanner.l"


/* Notes:
	[:digit:]+ doesn't work!  I spent a couple hours debugging that one!
	There are two copies of the interpreter.  src/rc, and tests/rc.
		src/rc is non-interactive, tests/rc is interactive.  They
		want to be merged if possible.
	Very very very basic, but it works!
	C++ style comments "//" work in bison but *not* in flex!!
*/

